/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sunflecks;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.*;
import javax.swing.SwingUtilities;
import au.com.bytecode.opencsv.CSVReader;
import au.com.bytecode.opencsv.CSVWriter;
import java.io.FileReader;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JRadioButton;


/**
 *
 * @author lfhan
 */
public class MainFrame extends javax.swing.JFrame {
    
    JFileChooser fc;
    File inputfile;
    File outputfile;
    String[][] allPara;
    Object[][] tableData;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws FileNotFoundException, IOException {
        CSVReader reader = new CSVReader(new FileReader("para.csv"));
        List<String[]> paraList = reader.readAll();
        this.allPara = paraList.toArray(new String[0][]);  
        initComponents();       
        fc = new JFileChooser();
        FileFilter ff=new FileFilter(){
            public boolean accept(File f) {
                String fName = f.getName().toUpperCase();
                if (fName.endsWith(".CSV") || f.isDirectory()) {
                    return true;
                } else {
                    return false;   
                }
            }
            
            public String getDescription() {
                return "CSV File (*.csv)";
            }
        };            
        fc.setFileFilter(ff);      
        inputfile= new File("input.csv");
        outputfile= new File("output.csv");
        txtInput.setText(inputfile.getAbsolutePath());
        txtOutput.setText(outputfile.getAbsolutePath());
//        tableData = new Object[36][2];
//        for (int i = 0 ; i < 36 ; i++) {
//            for (int j = 0 ; j < 2 ; j++) {
//                tableData[i][j] = paraTable.getValueAt(i,j);
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeBtnGroup = new javax.swing.ButtonGroup();
        runBtn = new javax.swing.JButton();
        iniPARtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputBtn = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        outputBtn = new javax.swing.JButton();
        txtOutput = new javax.swing.JTextField();
        paraScrollPane = new javax.swing.JScrollPane();
        paraTable = new javax.swing.JTable();
        DynRadioBtn = new javax.swing.JRadioButton();
        StdyRadioBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        runBtn.setText("run model");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });

        iniPARtxt.setText("100");

        jLabel1.setText("Initial PAR");

        inputBtn.setText("Choose Input");
        inputBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBtnActionPerformed(evt);
            }
        });

        outputBtn.setText("Choose Output");
        outputBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputBtnActionPerformed(evt);
            }
        });

        paraTable.setModel(new javax.swing.table.DefaultTableModel(
            this.allPara,
            new String [] {
                "Parameters", "Values"
            }
        ){
            public boolean isCellEditable(int row, int column){
                if (column == 0) {
                    return false;
                } else {
                    return true;
                }
            }
        });
        paraScrollPane.setViewportView(paraTable);

        modeBtnGroup.add(DynRadioBtn);
        DynRadioBtn.setText("Dynamic Mode");
        DynRadioBtn.setSelected(true);

        modeBtnGroup.add(StdyRadioBtn);
        StdyRadioBtn.setText("Steady Mode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputBtn)
                            .addComponent(outputBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(runBtn)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(txtInput, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(iniPARtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DynRadioBtn)
                            .addComponent(StdyRadioBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(paraScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {inputBtn, outputBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DynRadioBtn, StdyRadioBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBtn)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputBtn)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(DynRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StdyRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(iniPARtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(runBtn)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(paraScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {iniPARtxt, jLabel1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        tableData = new Object[36][2];
        Map<String, Double> paraMap = new HashMap<>();
        boolean ifdyn=DynRadioBtn.isSelected();
        for (int i = 0 ; i < 36 ; i++) {
            String key = (String) paraTable.getValueAt(i,0);
            Double value= Double.parseDouble((String) paraTable.getValueAt(i,1));
            paraMap.put(key,value);
        }
        try {   
            double iniPAR = Double.parseDouble(iniPARtxt.getText());
            Sunflecks.run(iniPAR,inputfile,outputfile,paraMap,ifdyn);
        } catch (NoSuchFieldException | IllegalAccessException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_runBtnActionPerformed

    private void inputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBtnActionPerformed

        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.inputfile = fc.getSelectedFile();
            txtInput.setText(inputfile.getAbsolutePath());
        }
    }//GEN-LAST:event_inputBtnActionPerformed

    private void outputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputBtnActionPerformed
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.outputfile = fc.getSelectedFile();
            txtOutput.setText(outputfile.getAbsolutePath());
        }
    }//GEN-LAST:event_outputBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DynRadioBtn;
    private javax.swing.JRadioButton StdyRadioBtn;
    private javax.swing.JTextField iniPARtxt;
    private javax.swing.JButton inputBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup modeBtnGroup;
    private javax.swing.JButton outputBtn;
    private javax.swing.JScrollPane paraScrollPane;
    private javax.swing.JTable paraTable;
    private javax.swing.JButton runBtn;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
